import React, { useRef } from 'react';
import { Camera, Receipt } from 'lucide-react';
import html2canvas from 'html2canvas';
import { formatCurrency } from '../utils/formatCurrency';

export default function Summary({ people, items, tax, serviceTax }) {
  const printRef = useRef(null);

  const calculateSplit = () => {
    let totals = {};
    people.forEach(p => totals[p.id] = { name: p.name, subtotal: 0, tax: 0, service: 0, total: 0, items: [] });
    
    let globalSubtotal = 0;

    items.forEach(item => {
      globalSubtotal += item.price;
      const amountPerPerson = item.price / item.assignedTo.length;
      item.assignedTo.forEach(personId => {
        if (totals[personId]) {
          totals[personId].subtotal += amountPerPerson;
          totals[personId].items.push({ name: item.name, amount: amountPerPerson });
        }
      });
    });

    const taxAmount = globalSubtotal * (tax / 100);
    const serviceAmount = globalSubtotal * (serviceTax / 100);
    const grandTotal = globalSubtotal + taxAmount + serviceAmount;

    let results = [];
    Object.values(totals).forEach(person => {
      if (globalSubtotal > 0) {
        const proportion = person.subtotal / globalSubtotal;
        person.tax = proportion * taxAmount;
        person.service = proportion * serviceAmount;
      }
      person.total = person.subtotal + person.tax + person.service;
      if (person.total > 0 || person.items.length > 0) {
        results.push(person);
      }
    });

    return { globalSubtotal, taxAmount, serviceAmount, grandTotal, results };
  };

  const { globalSubtotal, taxAmount, serviceAmount, grandTotal, results } = calculateSplit();

  const handleDownloadImage = async () => {
    if (printRef.current) {
      const element = printRef.current;
      const canvas = await html2canvas(element, { 
        backgroundColor: '#1e1e2f',
        scale: 2 
      });
      const data = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.href = data;
      link.download = `split-bill-${new Date().getTime()}.png`;
      link.click();
    }
  };

  if (items.length === 0) {
    return (
      <div className="summary-container" style={{textAlign: 'center', opacity: 0.5}}>
        <Receipt size={48} style={{marginBottom: '1rem', opacity: 0.5}} />
        <h3>Ringkasan Tagihan</h3>
        <p>Belum ada pesanan untuk dihitung.</p>
      </div>
    );
  }

  return (
    <div>
      <div className="summary-container" ref={printRef}>
        <div className="card-title" style={{color: 'white', borderColor: 'rgba(255,255,255,0.1)'}}>
          <Receipt size={24} color="#ec4899" /> Ringkasan Tagihan
        </div>

        <div className="summary-row">
          <span>Subtotal</span>
          <span>{formatCurrency(globalSubtotal)}</span>
        </div>
        <div className="summary-row">
          <span>Service Charge ({serviceTax}%)</span>
          <span>{formatCurrency(serviceAmount)}</span>
        </div>
        <div className="summary-row">
          <span>Tax / PPN ({tax}%)</span>
          <span>{formatCurrency(taxAmount)}</span>
        </div>
        <div className="summary-row total">
          <span>Grand Total</span>
          <span>{formatCurrency(grandTotal)}</span>
        </div>

        <div style={{marginTop: '2rem'}}>
          <h4 style={{color: 'white', marginBottom: '1rem', fontFamily: "'Outfit', sans-serif"}}>Tagihan Per Orang</h4>
          {results.map((person, index) => (
            <div key={index} className="person-bill">
              <div className="person-header">
                <span>{person.name}</span>
                <span className="person-total">{formatCurrency(person.total)}</span>
              </div>
              <div style={{marginTop: '0.75rem', marginBottom: '0.75rem'}}>
                {person.items.map((it, idx) => (
                  <div key={idx} className="person-detail">
                    <span>{it.name}</span>
                    <span>{formatCurrency(it.amount)}</span>
                  </div>
                ))}
              </div>
              <div style={{borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '0.5rem'}}>
                <div className="person-detail">
                  <span>Service + Tax Proportion</span>
                  <span>{formatCurrency(person.service + person.tax)}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
        {/* Adds a small footer attribution to the downloaded image */}
        <div style={{textAlign: 'center', fontSize: '0.75rem', color: 'rgba(255,255,255,0.3)', marginTop: '2rem'}}>
          Generated by Split Bill App
        </div>
      </div>

      <div className="action-bar">
        <button className="btn btn-primary" onClick={handleDownloadImage} style={{width: '100%'}}>
          <Camera size={18} /> Download Gambar
        </button>
      </div>
    </div>
  );
}
